# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Forecast Name"),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Target Amount",
                    ),
                ),
                (
                    "pipeline_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                        verbose_name="Pipeline Amount",
                    ),
                ),
                (
                    "best_case_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                        verbose_name="Best Case Amount",
                    ),
                ),
                (
                    "commit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                        verbose_name="Commit Amount",
                    ),
                ),
                (
                    "closed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                        verbose_name="Closed Amount",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                        verbose_name="Actual Amount",
                    ),
                ),
                (
                    "target_quantity",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Target Quantity"
                    ),
                ),
                (
                    "pipeline_quantity",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Pipeline Quantity",
                    ),
                ),
                (
                    "best_case_quantity",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Best Case Quantity",
                    ),
                ),
                (
                    "commit_quantity",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Commit Quantity"
                    ),
                ),
                (
                    "closed_quantity",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Closed Quantity"
                    ),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Actual Quantity"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Forecast",
                "verbose_name_plural": "Forecasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("field", models.CharField(max_length=100, verbose_name="Field Name")),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (
                                "text",
                                [
                                    ("icontains", "Contains"),
                                    ("exact", "Equals"),
                                    ("ne", "Not Equals"),
                                    ("istartswith", "Starts with"),
                                    ("iendswith", "Ends with"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "number",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "Greater than"),
                                    ("lt", "Less than"),
                                    ("gte", "Greater than or equal"),
                                    ("lte", "Less than or equal"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "float",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "Greater than"),
                                    ("lt", "Less than"),
                                    ("gte", "Greater than or equal"),
                                    ("lte", "Less than or equal"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "decimal",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "Greater than"),
                                    ("lt", "Less than"),
                                    ("gte", "Greater than or equal"),
                                    ("lte", "Less than or equal"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "date",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "After"),
                                    ("lt", "Before"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "datetime",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "After"),
                                    ("lt", "Before"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            ("boolean", [("exact", "Equals")]),
                            (
                                "choice",
                                [
                                    ("exact", "Equals"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "other",
                                [
                                    ("exact", "Equals"),
                                    ("icontains", "Contains"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                        ],
                        max_length=50,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "value",
                    models.CharField(blank=True, max_length=255, verbose_name="Value"),
                ),
                (
                    "logical_operator",
                    models.CharField(
                        choices=[("and", "AND"), ("or", "OR")],
                        default="and",
                        max_length=3,
                        verbose_name="Logical Operator",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Forecast Condition",
                "verbose_name_plural": "Forecast Conditions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target amount (revenue or quantity)",
                        max_digits=18,
                        verbose_name="Target",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (e.g., USD, EUR, INR)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current achieved amount (auto-calculated)",
                        max_digits=18,
                        verbose_name="Current Achievement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Target",
                "verbose_name_plural": "Forecast Targets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastTargetUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "revenue_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Individual revenue target for this user",
                        max_digits=18,
                        verbose_name="User Revenue Target",
                    ),
                ),
                (
                    "quantity_target",
                    models.IntegerField(
                        default=0,
                        help_text="Individual quantity target for this user",
                        verbose_name="User Quantity Target",
                    ),
                ),
                (
                    "current_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current achieved revenue for this user",
                        max_digits=18,
                        verbose_name="Current Revenue Achieved",
                    ),
                ),
                (
                    "current_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Current achieved quantity for this user",
                        verbose_name="Current Quantity Achieved",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Forecast Target User",
                "verbose_name_plural": "Forecast Target Users",
            },
        ),
        migrations.CreateModel(
            name="ForecastType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Forecast Type Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("deal_revenue_amount", "Deal Revenue Amount"),
                            (
                                "deal_revenue_expected_amount",
                                "Deal Revenue Expected Amount",
                            ),
                            ("deal_quantity", "Deal Quantity"),
                        ],
                        default="deal_revenue_amount",
                        max_length=50,
                        verbose_name="Forecast Type",
                    ),
                ),
                (
                    "include_pipeline",
                    models.BooleanField(default=True, verbose_name="Include Pipeline"),
                ),
                (
                    "include_best_case",
                    models.BooleanField(default=True, verbose_name="Include Best Case"),
                ),
                (
                    "include_commit",
                    models.BooleanField(default=True, verbose_name="Include Commit"),
                ),
                (
                    "include_closed",
                    models.BooleanField(default=True, verbose_name="Include Closed"),
                ),
            ],
            options={
                "verbose_name": "Forecast Type",
                "verbose_name_plural": "Forecast Types",
            },
        ),
    ]
