# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("contacts", "0001_initial"),
        ("horilla_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BigDealAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "alert_name",
                    models.CharField(max_length=255, verbose_name="Alert Name"),
                ),
                (
                    "trigger_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Trigger Amount",
                    ),
                ),
                (
                    "trigger_probability",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Trigger alert when opportunity probability reaches this percentage",
                        verbose_name="Trigger Probability",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sender Name",
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Sender Email",
                    ),
                ),
                (
                    "notify_emails",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated emails to notify",
                        null=True,
                        verbose_name="Notify Emails",
                    ),
                ),
                (
                    "notify_cc_emails",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notify CC Emails"
                    ),
                ),
                (
                    "notify_bcc_emails",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notify BCC Emails"
                    ),
                ),
                (
                    "notify_opportunity_owner",
                    models.BooleanField(
                        default=False, verbose_name="Notify Opportunity Owner"
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Big Deal Alert",
                "verbose_name_plural": "Big Deal Alerts",
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Opportunity Name",
                        max_length=120,
                        verbose_name="Opportunity Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Expected Revenue",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total Opportunity Quantity",
                        max_digits=16,
                        null=True,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "close_date",
                    models.DateField(blank=True, null=True, verbose_name="Close Date"),
                ),
                (
                    "probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Probability percentage (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Probability",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=32000, verbose_name="Description"
                    ),
                ),
                (
                    "next_step",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Next Step"
                    ),
                ),
                (
                    "opportunity_score",
                    models.IntegerField(default=0, verbose_name="Opportunity Score"),
                ),
                (
                    "opportunity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "existing_customer_upgrade",
                                "Existing Customer - Upgrade",
                            ),
                            (
                                "existing_customer_replacement",
                                "Existing Customer - Replacement",
                            ),
                            (
                                "existing_customer_downgrade",
                                "Existing Customer - Downgrade",
                            ),
                            ("new_customer", "New Customer"),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("event", "Event"),
                            ("campaign", "Campaign"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("social media", "Social Media"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "forecast_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("omitted", "Omitted"),
                            ("pipeline", "Pipeline"),
                            ("best_case", "Best Case"),
                            ("commit", "Commit"),
                            ("closed", "Closed"),
                        ],
                        max_length=50,
                        verbose_name="Forecast Category",
                    ),
                ),
                (
                    "delivery_installation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yet_to_fulfill", "Yet to Fulfill"),
                            ("partially_delivered", "Partially Delivered"),
                            ("completely_delivered", "Completely Delivered"),
                        ],
                        max_length=50,
                        verbose_name="Delivery Installation Status",
                    ),
                ),
                (
                    "main_competitors",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Main Competitors"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Order Number"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity_account",
                        to="accounts.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Opportunity Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "primary_campaign_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="campaigns.campaign",
                        verbose_name="Primary Campaign Source",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunitySplitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "split_label",
                    models.CharField(
                        help_text="Name of the split type (e.g., Revenue, Overlay)",
                        max_length=255,
                        unique=True,
                        verbose_name="Split Label",
                    ),
                ),
                (
                    "split_field",
                    models.CharField(
                        choices=[
                            ("amount", "Opportunity - Amount"),
                            ("expected_revenue", "Opportunity - Expected Revenue"),
                        ],
                        default="amount",
                        help_text="Field to split: amount, expected_revenue, etc.",
                        max_length=100,
                        verbose_name="Split Field",
                    ),
                ),
                (
                    "totals_100_percent",
                    models.BooleanField(
                        default=True,
                        help_text="Require splits of this type to total exactly 100%",
                        verbose_name="Totals 100%",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Split Type",
                "verbose_name_plural": "Opportunity Split Types",
                "unique_together": {("company", "split_field", "totals_100_percent")},
            },
        ),
        migrations.CreateModel(
            name="OpportunitySplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "split_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total credit (e.g., 25.00 for 25%).",
                        max_digits=6,
                        null=True,
                        verbose_name="Split Percentage",
                    ),
                ),
                (
                    "split_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated split amount based on percentage and opportunity amount.",
                        max_digits=15,
                        null=True,
                        verbose_name="Split Amount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="opportunities.opportunity",
                        verbose_name="Opportunity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving credit for this split.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_splits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Member",
                    ),
                ),
                (
                    "split_type",
                    models.ForeignKey(
                        help_text="Type of split, such as Revenue or Overlay.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="opportunities.opportunitysplittype",
                        verbose_name="Split Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpportunityStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Stage Name")),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order in which stages appear", verbose_name="Order"
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default probability percentage for this stage",
                        max_digits=5,
                        verbose_name="Probability",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="Is Final Stage"),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("won", "Closed Won"),
                            ("lost", "Closed Lost"),
                        ],
                        default="open",
                        help_text="Type of stage - Open, Closed Won, or Closed Lost",
                        max_length=10,
                        verbose_name="Stage Type",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Stage",
                "verbose_name_plural": "Opportunity Stages",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="stage",
            field=models.ForeignKey(
                help_text="Current opportunity stage",
                on_delete=django.db.models.deletion.PROTECT,
                to="opportunities.opportunitystage",
                verbose_name="Stage",
            ),
        ),
        migrations.CreateModel(
            name="OpportunityTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "team_name",
                    models.CharField(max_length=255, verbose_name="Team Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Team",
                "verbose_name_plural": "Opportunity Teams",
            },
        ),
        migrations.CreateModel(
            name="DefaultOpportunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "team_role",
                    models.CharField(
                        choices=[
                            ("account_manager", "Account Manager"),
                            ("channel_manager", "Channel Manager"),
                            ("executive_sponsor", "Executive Sponsor"),
                            ("lead_qualifier", "Lead Qualifier"),
                            ("pre_sales_consultant", "Pre-Sales Consultant"),
                            ("sales_manager", "Sales Manager"),
                            ("sales_rep", "Sales Rep"),
                            ("opportunity_owner", "Opportunity Owner"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Member Role",
                    ),
                ),
                (
                    "opportunity_access_level",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("edit", "Read/Write"),
                            ("owner", "Owner"),
                        ],
                        max_length=20,
                        verbose_name="Access Level",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_opportunity_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Member",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="opportunities.opportunityteam",
                        verbose_name="Team Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Opportunity Member",
                "verbose_name_plural": "Default Opportunity Members",
            },
        ),
        migrations.CreateModel(
            name="OpportunityTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "opportunity_access",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("edit", "Read/Write"),
                            ("owner", "Owner"),
                        ],
                        default="Read",
                        max_length=255,
                        verbose_name="Opportunity Access",
                    ),
                ),
                (
                    "team_role",
                    models.CharField(
                        choices=[
                            ("account_manager", "Account Manager"),
                            ("channel_manager", "Channel Manager"),
                            ("executive_sponsor", "Executive Sponsor"),
                            ("lead_qualifier", "Lead Qualifier"),
                            ("pre_sales_consultant", "Pre-Sales Consultant"),
                            ("sales_manager", "Sales Manager"),
                            ("sales_rep", "Sales Rep"),
                            ("opportunity_owner", "Opportunity Owner"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Member Role",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_team_members",
                        to="opportunities.opportunity",
                        verbose_name="Opportunity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunty_team_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Team Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity team member",
                "verbose_name_plural": "Opportunity team members",
            },
        ),
        migrations.CreateModel(
            name="OpportunityContactRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_roles",
                        to="contacts.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_roles",
                        to="opportunities.opportunity",
                        verbose_name="Opportunity",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_contact_roles",
                        to="horilla_core.customerrole",
                        verbose_name="Role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Contact Role",
                "verbose_name_plural": "Opportunity Contact Roles",
                "unique_together": {("contact", "opportunity")},
            },
        ),
        migrations.CreateModel(
            name="OpportunitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "team_selling_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable Opportunity Teams to help multiple users collaborate on opportunities. When enabled, you can define roles for team members, set record-level access, and view teams in list views and reports.",
                        verbose_name="Enable Team Selling",
                    ),
                ),
                (
                    "split_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Allow multiple users to share credit for an opportunity. Splits can be based on revenue, overlay, or custom metrics.",
                        verbose_name="Enable Opportunity Splits",
                    ),
                ),
                (
                    "allow_all_users_in_splits",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, users can assign splits to any active user in the company, not just opportunity team members. This allows adding new members while editing splits.",
                        verbose_name="Let users add members to opportunity teams while editing splits",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Setting",
                "verbose_name_plural": "Opportunity Settings",
                "unique_together": {("company",)},
            },
        ),
        migrations.AddConstraint(
            model_name="opportunitystage",
            constraint=models.UniqueConstraint(
                fields=("name", "company"), name="unique_stage_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunitystage",
            constraint=models.UniqueConstraint(
                fields=("order", "company"), name="unique_stage_order_per_company"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="defaultopportunitymember",
            unique_together={("user", "team")},
        ),
    ]
