# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Account Name")),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Account Number"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prospect", "Prospect"),
                            ("customer_direct", "Customer - Direct"),
                            ("customer_channel", "Customer - Channel"),
                            ("channel_partner_reseller", "Channel Partner / Reseller"),
                            ("installation_partner", "Installation Partner"),
                            ("technology_partner", "Technology Partner"),
                            ("other", "Other"),
                        ],
                        max_length=80,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Account Site"
                    ),
                ),
                (
                    "account_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("event", "Event"),
                            ("campaign", "Campaign"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("social media", "Social Media"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Account Source",
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=18,
                        null=True,
                        verbose_name="Annual Revenue",
                    ),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing City"
                    ),
                ),
                (
                    "billing_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing State"
                    ),
                ),
                (
                    "billing_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing District"
                    ),
                ),
                (
                    "billing_zip",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Billing Zip"
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shipping City"
                    ),
                ),
                (
                    "shipping_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shipping State"
                    ),
                ),
                (
                    "shipping_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shipping District"
                    ),
                ),
                (
                    "shipping_zip",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Shipping Zip"
                    ),
                ),
                (
                    "is_customer_portal",
                    models.BooleanField(
                        default=False, verbose_name="Is Customer Portal"
                    ),
                ),
                (
                    "customer_priority",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Customer Priority"
                    ),
                ),
                (
                    "is_partner",
                    models.BooleanField(default=False, verbose_name="Is Partner"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=32000, verbose_name="Description"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("finance", "Finance"),
                            ("healthcare", "Healthcare"),
                            ("manufacturing", "Manufacturing"),
                            ("agriculture", "Agriculture"),
                            ("construction", "Construction"),
                            ("banking", "Banking"),
                            ("education", "Education"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Industry",
                    ),
                ),
                (
                    "number_of_employees",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Employees"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Phone"),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=40, verbose_name="Fax"),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=255, verbose_name="Website"),
                ),
                (
                    "operating_hours",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Operating Hours"
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("subsidiary", "Subsidiary"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Ownership",
                    ),
                ),
                (
                    "rating",
                    models.CharField(blank=True, max_length=255, verbose_name="Rating"),
                ),
                (
                    "account_score",
                    models.IntegerField(default=0, verbose_name="Account Score"),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="PartnerAccountRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Account Role",
                "verbose_name_plural": "Partner Account Roles",
            },
        ),
    ]
