# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="Subject")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("meeting", "Meeting"),
                            ("task", "Task"),
                            ("log_call", "Log Call"),
                        ],
                        max_length=20,
                        verbose_name="Activity Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Source"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Related Object ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "is_all_day",
                    models.BooleanField(default=False, verbose_name="All Day"),
                ),
                (
                    "task_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "due_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Due Date"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Recipient Email",
                    ),
                ),
                (
                    "call_duration_display",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Call Duration",
                    ),
                ),
                (
                    "call_duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Call Duration (Seconds)"
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        blank=True,
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=50,
                        null=True,
                        verbose_name="Call Type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "call_purpose",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Call Purpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
    ]
