# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(max_length=255, verbose_name="Campaign Name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("event", "Event"),
                            ("social_media", "Social Media"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Expected Revenue",
                    ),
                ),
                (
                    "budget_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Budget Cost",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Actual Cost",
                    ),
                ),
                (
                    "expected_response",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Expected Response (%)"
                    ),
                ),
                (
                    "number_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number Sent in Campaign"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "leads_in_campaign",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Leads in Campaign"
                    ),
                ),
                (
                    "converted_leads_in_campaign",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Converted Leads in Campaign"
                    ),
                ),
                (
                    "contacts_in_campaign",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contacts in Campaign"
                    ),
                ),
                (
                    "opportunities_in_campaign",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Opportunities in Campaign"
                    ),
                ),
                (
                    "won_opportunities_in_campaign",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Won Opportunities in Campaign"
                    ),
                ),
                (
                    "value_opportunities",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="Value Opportunities in Campaign",
                    ),
                ),
                (
                    "value_won_opportunities",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="Value Won Opportunities in Campaign",
                    ),
                ),
                (
                    "responses_in_campaign",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Responses in Campaign"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "member_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("sent", "Sent"),
                            ("recieved", "Recieved"),
                            ("responded", "Responded"),
                        ],
                        max_length=20,
                        verbose_name="Member Status",
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("lead", "Lead"), ("contact", "Contact")],
                        default="lead",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Member",
                "verbose_name_plural": "Campaign Members",
            },
        ),
    ]
