# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("contacts", "0002_initial"),
        ("horilla_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="campaign_owner",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Campaign Owner",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="parent_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_campaigns",
                to="campaigns.campaign",
                verbose_name="Parent Campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="campaignmember",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignmember",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="campaignmember",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_campaign_members",
                to="contacts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="campaignmember",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
    ]
