# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.db.models.deletion
import django.utils.timezone
import genie_core.models as horilla_core_models
import genie_mail.fields as horilla_mail_fields
import genie_mail.methods as horilla_mail_methods
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("horilla_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HorillaMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "to",
                    models.TextField(
                        help_text="Comma separated recipient email addresses",
                        verbose_name="To",
                    ),
                ),
                ("cc", models.TextField(blank=True, null=True, verbose_name="Cc")),
                ("bcc", models.TextField(blank=True, null=True, verbose_name="Bcc")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Subject"
                    ),
                ),
                ("body", models.TextField(blank=True, null=True, verbose_name="Body")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "mail_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("mail_status_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the mail should be sent (for scheduled mails).",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
            },
        ),
        migrations.CreateModel(
            name="HorillaMailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("file", models.FileField(upload_to=horilla_core_models.upload_path)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("is_inline", models.BooleanField(default=False)),
                ("content_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="horilla_mail.horillamail",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail Attachment",
                "verbose_name_plural": "Mail Attachments",
            },
        ),
        migrations.CreateModel(
            name="HorillaMailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("mail", "Mail"), ("outlook", "Outlook")],
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "mail_channel",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        help_text="Specifies whether this configuration handles incoming, outgoing, or both types of emails.",
                        max_length=20,
                        verbose_name="Mail Channel",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Host"
                    ),
                ),
                (
                    "port",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Port"
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        max_length=256, null=True, verbose_name="Default From Mail"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Email Host Username",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Display Name"
                    ),
                ),
                (
                    "password",
                    horilla_mail_fields.EncryptedCharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Email Authentication Password",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Use TLS"
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Use SSL"
                    ),
                ),
                (
                    "fail_silently",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Fail Silently",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Primary Mail Server"
                    ),
                ),
                (
                    "use_dynamic_display_name",
                    models.BooleanField(
                        default=True,
                        help_text="By enabling this the display name will take from who triggered the mail",
                    ),
                ),
                (
                    "timeout",
                    models.SmallIntegerField(
                        null=True, verbose_name="Email Send Timeout (seconds)"
                    ),
                ),
                (
                    "outlook_client_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Client ID"
                    ),
                ),
                (
                    "outlook_client_secret",
                    horilla_mail_fields.EncryptedCharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Client Secret",
                    ),
                ),
                (
                    "outlook_tenant_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Tenant ID"
                    ),
                ),
                (
                    "outlook_redirect_uri",
                    models.URLField(blank=True, null=True, verbose_name="Redirect URi"),
                ),
                (
                    "outlook_authorization_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="OAuth authorization endpoint",
                    ),
                ),
                (
                    "outlook_token_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="OAuth token endpoint"
                    ),
                ),
                (
                    "outlook_api_endpoint",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Microsoft Graph API endpoint",
                    ),
                ),
                ("token", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "oauth_state",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
                (
                    "last_refreshed",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail Configuration",
                "verbose_name_plural": "Mail Configurations",
            },
        ),
        migrations.AddField(
            model_name="horillamail",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_mails",
                to="horilla_mail.horillamailconfiguration",
                verbose_name="From",
            ),
        ),
        migrations.CreateModel(
            name="HorillaMailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Template title"),
                ),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=horilla_mail_methods.limit_content_types,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.horillacontenttype",
                        verbose_name="Related Model",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail Template",
                "verbose_name_plural": "Mail Templates",
                "unique_together": {("title", "company")},
            },
        ),
    ]
