# Generated by Django 5.2.8 on 2025-11-17 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import genie_core.models as horilla_core_models
import genie_dashboard.methods as horilla_dashboard_methods
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("horilla_core", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Dashboard Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Is Default"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dashboard_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horilla_dashboard",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dashboard Owner",
                    ),
                ),
                (
                    "favourited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favourite_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Favourited By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Component Name"),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("chart", "Charts"),
                            ("table_data", "Table Data"),
                            ("kpi", "KPI"),
                        ],
                        max_length=50,
                        verbose_name="Component Type",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("column", "Column Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("funnel", "Funnel"),
                            ("bar", "Bar Chart"),
                            ("donut", "Donut"),
                            ("stacked_vertical", "Stacked Vertical Chart"),
                            ("stacked_horizontal", "Stacked Horizontal Chart"),
                        ],
                        default="column",
                        max_length=50,
                        null=True,
                        verbose_name="Chart Type",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("count", "Count"),
                            ("sum", "Sum"),
                            ("average", "Average"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                        ],
                        default="count",
                        max_length=50,
                        null=True,
                        verbose_name="Metric Type",
                    ),
                ),
                (
                    "grouping_field",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Grouping Field",
                    ),
                ),
                (
                    "secondary_grouping",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Secondary Grouping (For Stacked)",
                    ),
                ),
                (
                    "columns",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Table Columns",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sequence",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=horilla_core_models.upload_path,
                        verbose_name="KPI Icon",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "component_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Component Owner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="horilla_dashboard.dashboard",
                        verbose_name="Dashboard",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                    limit_choices_to=horilla_dashboard_methods.limit_content_types,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.horillacontenttype",
                        verbose_name="Module",
                    ),
                ),
                (
                    "reports",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horilla_dashboard",
                        to="reports.report",
                        verbose_name="Reports",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Component",
                "verbose_name_plural": "Dashboard Components",
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComponentCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("field", models.CharField(max_length=100, verbose_name="Field Name")),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (
                                "text",
                                [
                                    ("icontains", "Contains"),
                                    ("exact", "Equals"),
                                    ("ne", "Not Equals"),
                                    ("istartswith", "Starts with"),
                                    ("iendswith", "Ends with"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "number",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "Greater than"),
                                    ("lt", "Less than"),
                                    ("gte", "Greater than or equal"),
                                    ("lte", "Less than or equal"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "float",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "Greater than"),
                                    ("lt", "Less than"),
                                    ("gte", "Greater than or equal"),
                                    ("lte", "Less than or equal"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "decimal",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "Greater than"),
                                    ("lt", "Less than"),
                                    ("gte", "Greater than or equal"),
                                    ("lte", "Less than or equal"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "date",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "After"),
                                    ("lt", "Before"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "datetime",
                                [
                                    ("exact", "Equals"),
                                    ("gt", "After"),
                                    ("lt", "Before"),
                                    ("between", "Between"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            ("boolean", [("exact", "Equals")]),
                            (
                                "choice",
                                [
                                    ("exact", "Equals"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                            (
                                "other",
                                [
                                    ("exact", "Equals"),
                                    ("icontains", "Contains"),
                                    ("isnull", "Is empty"),
                                    ("isnotnull", "Is not empty"),
                                ],
                            ),
                        ],
                        max_length=50,
                        verbose_name="Operator",
                    ),
                ),
                (
                    "value",
                    models.CharField(blank=True, max_length=255, verbose_name="Value"),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=1, verbose_name="Sequence"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="horilla_dashboard.dashboardcomponent",
                        verbose_name="Component",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component Criteria",
                "verbose_name_plural": "Component Criteria",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="DashboardFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Folder Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "favourited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favourite_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Favourited By",
                    ),
                ),
                (
                    "folder_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Folder Owner",
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="horilla_dashboard.dashboardfolder",
                        verbose_name="Folder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Folder",
                "verbose_name_plural": "Dashboard Folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dashboard",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horilla_dashboard",
                to="horilla_dashboard.dashboardfolder",
                verbose_name="Folder",
            ),
        ),
    ]
