# Generated by Django 5.2.8 on 2025-11-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=80, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=80, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="City"
                    ),
                ),
                (
                    "address_state",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="State"
                    ),
                ),
                (
                    "address_zip",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Zip"
                    ),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "contact_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web"),
                            ("phone_inquiry", "Phone Inquiry"),
                            ("partner_referral", "Partner Referral"),
                            ("purchased_list", "Purchased List"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Contact Source",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth Date"),
                ),
                (
                    "assistant",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Assistant"
                    ),
                ),
                (
                    "assistant_phone",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Assistant Phone",
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Languages",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "contact_score",
                    models.IntegerField(default=0, verbose_name="Contact Score"),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="ContactAccountRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Account Relationship",
                "verbose_name_plural": "Contact Account Relationships",
            },
        ),
    ]
